jmxsh.commands.name=quit,open,close,domains,domain,beans,bean,info,get,set,run,option,jvms,about,watch,subscribe,unsubscribe
jmxsh.commands.quit.type=org.cyclopsgroup.jmxterm.cmd.QuitCommand
jmxsh.commands.quit.alias=exit,bye
jmxsh.commands.open.type=org.cyclopsgroup.jmxterm.cmd.OpenCommand
jmxsh.commands.close.type=org.cyclopsgroup.jmxterm.cmd.CloseCommand
jmxsh.commands.domains.type=org.cyclopsgroup.jmxterm.cmd.DomainsCommand
jmxsh.commands.domain.type=org.cyclopsgroup.jmxterm.cmd.DomainCommand
jmxsh.commands.beans.type=org.cyclopsgroup.jmxterm.cmd.BeansCommand
jmxsh.commands.bean.type=org.cyclopsgroup.jmxterm.cmd.BeanCommand
jmxsh.commands.info.type=org.cyclopsgroup.jmxterm.cmd.InfoCommand
jmxsh.commands.get.type=org.cyclopsgroup.jmxterm.cmd.GetCommand
jmxsh.commands.set.type=org.cyclopsgroup.jmxterm.cmd.SetCommand
jmxsh.commands.run.type=org.cyclopsgroup.jmxterm.cmd.RunCommand
jmxsh.commands.option.type=org.cyclopsgroup.jmxterm.cmd.OptionCommand
jmxsh.commands.jvms.type=org.cyclopsgroup.jmxterm.cmd.JvmsCommand
jmxsh.commands.about.type=org.cyclopsgroup.jmxterm.cmd.AboutCommand
jmxsh.commands.watch.type=org.cyclopsgroup.jmxterm.cmd.WatchCommand
jmxsh.commands.subscribe.type=org.cyclopsgroup.jmxterm.cmd.SubscribeCommand
jmxsh.commands.unsubscribe.type=org.cyclopsgroup.jmxterm.cmd.UnsubscribeCommand

jmxsh.about.software.name=jmxsh
jmxsh.about.software.description=Interactive command-line JMX client
jmxsh.about.software.url=https://github.com/nyg/jmxsh
jmxsh.about.release.version=1.1.0
jmxsh.about.release.date=2025-03-01
jmxsh.about.release.note=Fork actively maintained by nyg
jmxsh.about.author.id=jiaqi
jmxsh.about.author.jiaqi.name=Jiaqi Guo
jmxsh.about.author.jiaqi.email=jiaqi.guo@gmail.com
jmxsh.about.org.id=cyclopsgroup
jmxsh.about.org.cyclopsgroup.name=CyclopsGroup
jmxsh.about.org.cyclopsgroup.url=http://www.cyclopsgroup.org
