software.name=jmxsh
software.description=Interactive command-line JMX client
software.url=https://github.com/nyg/jmxsh
release.version=${project.version}
release.note=Fork actively maintained by nyg
author.name=Jiaqi Guo
author.email=jiaqi.guo@gmail.com
org.name=CyclopsGroup
org.url=http://www.cyclopsgroup.org
